<?php

/**
 * @file
 * Contains er_viewmode.module
 */

use Drupal\Core\Routing\RouteMatchInterface;
use Drupal\Core\Form\FormStateInterface;

/**
 * Implements hook_help().
 */
function er_viewmode_help($route_name, RouteMatchInterface $route_match) {
  switch ($route_name) {
    // Main module help for the er_viewmode module.
    case 'help.page.er_viewmode':
      $description = 'Provides an entity reference field with a view mode selector. ' .
        'This allows you, for each entity reference field instance, to specify the view mode '.
        'for rendering the referenced entity.';
      $output = '';
      $output .= '<h3>' . t('About') . '</h3>';
      $output .= '<p>' . t($description) . '</p>';
      return $output;
    break;
  }
}

/**
 * Implements hook_field_widget_form_alter().
 */
function er_viewmode_field_widget_form_alter(&$element, FormStateInterface $form_state, $context) {
  // Only alter entity reference view mode fields.
  $field_definition = $context['items']->getFieldDefinition();
  if ($field_definition->getType() == 'er_viewmode') {
    $settings = $field_definition->getSettings();
    // Is view mode selection enabled?
    if ($settings['view_mode_settings']['view_mode_selector_enabled']) {
      $view_modes = $settings['view_mode_settings']['allowed_view_modes'];
      $enabled_view_modes = array();
      $entity_type = $field_definition->getTargetEntityTypeId();
      foreach ($view_modes as $mode_id_key => $enabled) {
        if ($enabled) {
          $enabled_view_modes[$mode_id_key] = str_replace($entity_type . '__', '', $mode_id_key);
        }
      }

      if (count($enabled_view_modes) > 0) {
        // Get the view mode names.
        $all_view_modes = \Drupal::entityManager()->getAllViewModes();
        $view_mode_options = array('full' => t('Default'));
        foreach ($enabled_view_modes as $mode_id_key => $mode_id) {
          $view_mode_options[$mode_id] = $all_view_modes[$entity_type][$mode_id]['label'];
        }

        // Get the current item.
        $item = isset($context['items'][$context['delta']]) ? $context['items'][$context['delta']] : NULL;
        $default_view_mode = 'full';
        if (isset($item->view_mode)) {
          $default_view_mode = $item->view_mode;
        }

        // Add the view modes to the field widget.
        $element['view_mode'] = array(
          '#type' => 'select',
          '#title' => t('View Mode'),
          '#title_display' => 'invisible',
          '#options' => $view_mode_options,
          '#default_value' => $default_view_mode,
          '#weight' => 10,
        );
      }
    }
  }
}
